services:
  bluepanel-node:
    build:
      context: .
      dockerfile: Dockerfile
    image: bluepanel-node:local
    restart: always
    network_mode: host
    cap_add:
      - NET_ADMIN

    environment:
      SERVICE_PORT: 62050
      SERVICE_PROTOCOL: "grpc"
      PG_NODE_WG_HOST_ROUTING: "1"

      SSL_CERT_FILE: "/var/lib/bluepanel-node/certs/ssl_cert.pem"
      SSL_KEY_FILE: "/var/lib/bluepanel-node/certs/ssl_key.pem"
      # API_KEY must be a valid UUID.
      # API_KEY: xxxxxxxx-yyyy-zzzz-mmmm-aaaaaaaaaaa

      GENERATED_CONFIG_PATH: "/var/lib/bluepanel-node/generated"

    volumes:
      - /var/lib/bluepanel-node:/var/lib/bluepanel-node
