name: Create BluePanel Node Release

on:
  release:
    types: [created]

jobs:
  build:
    permissions:
      contents: write
    strategy:
      matrix:
        goos:
          - openbsd
          - linux
        goarch: [amd64, 386]
        gotoolchain: [""]
        patch-assetname: [""]
        include:
          - goos: linux
            goarch: arm
            goarm: 7
          - goos: linux
            goarch: arm
            goarm: 6
          - goos: linux
            goarch: arm
            goarm: 5
          - goos: linux
            goarch: arm64
          - goos: linux
            goarch: s390x
          - goos: openbsd
            goarch: arm64
      fail-fast: false

    runs-on: ubuntu-latest
    env:
      GOOS: ${{ matrix.goos }}
      GOARCH: ${{ matrix.goarch }}
      GOARM: ${{ matrix.goarm }}
      CGO_ENABLED: 0
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v7

      - name: Determine asset name
        run: |
          _GOARM="${GOARM:-}"
          if [ -n "$_GOARM" ]; then
            _NAME="${GOOS}-${GOARCH}-${_GOARM}"
          else
            _NAME="${GOOS}-${GOARCH}"
          fi
          echo "ASSET_NAME=$_NAME" >> "$GITHUB_ENV"

      - name: Set up Go
        uses: actions/setup-go@v7
        with:
          go-version: "1.26.3"
          check-latest: true

      - name: Get project dependencies
        run: make deps

      - name: Build binary and zip
        run: |
          make NAME="bluepanel-node-${ASSET_NAME}" build
          zip -9 "bluepanel-node-${ASSET_NAME}.zip" "bluepanel-node-${ASSET_NAME}" README.md LICENSE

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./bluepanel-node-${{ env.ASSET_NAME }}.zip
          asset_name: bluepanel-node-${{ env.ASSET_NAME }}.zip
          asset_content_type: application/zip
